export default [
    {word: 'ἀλλά', traduction: 'but'},
    {word: 'δέ', traduction: 'and/but'},
    {word: 'μαθητής, ὁ', traduction: 'disciple'},
    {word: 'παῖς, ὁ', traduction: 'kid/slave'},
    {word: 'φίλεω', traduction: 'to like'},
    {word: 'ζητέω', traduction: 'to seek'},
    {word: 'ἄνθρωπος, ὁ', traduction: 'man'},
    {word: 'ὁράω', traduction: 'to see'},
    {word: 'εἰμι', traduction: 'to be'},
    {word: 'νῦν', traduction: 'now'},
    {word: 'λόγος, ὁ', traduction: 'word'},
    {word: 'καλός, ή, όν', traduction: 'beautiful'},
    {word: 'κακός, ή, όν', traduction: 'ugly'},
    {word: 'θύρα, ἡ', traduction: 'gate'},
    {word: 'κελεύω', traduction: 'to command'},
    {word: 'ἤ', traduction: 'or'},
    {word: 'ἡδονή, ἡ', traduction: 'pleasure'},
    {word: 'τιμάω', traduction: 'to honor'},
    {word: 'πάσχω', traduction: 'to suffer'},
    {word: 'ἀποκρίνομαι', traduction: 'to answer'},
    {word: 'μανθάνω', traduction: 'to learn'},
    {word: 'ψυχή, ἡ', traduction: 'soul'},
    {word: 'δέχομαι', traduction: 'to receive'},
    {word: 'ναί', traduction: 'yes'},
    {word: 'ἀργός, ή, όν', traduction: 'lazy'},
    {word: 'φίλος, η, ον', traduction: 'friend'},
    {word: 'φρονέω', traduction: 'to think'},
    {word: 'μισέω', traduction: 'to hate'},
    {word: 'ἔρχομαι', traduction: 'to go/come'},
    {word: 'ἔχω', traduction: 'to have'},
    {word: 'ἐζαίφνης', traduction: 'suddenly'},
    {word: 'μήτηρ, ἡ', traduction: 'mother'},
    {word: 'παύω', traduction: 'to stop'},
    {word: 'ἀνήρ, ὁ', traduction: 'man/husband'},
    {word: 'ζωή, ἡ', traduction: 'life'},
    {word: 'ὀλοφύρομαι', traduction: 'to lament'},
    {word: 'μάθησις', traduction: 'learning'},
    {word: 'ποιέω', traduction: 'to do'},
    {word: 'γίγνομαι', traduction: 'to become'},
    {word: 'μεταξύ', traduction: 'between'},
    {word: 'λέγω', traduction: 'to say'},
    {word: 'εἰ', traduction: 'if'},
    {word: 'υἱός, ὁ', traduction: 'son'},
    {word: 'θεός, ὁ', traduction: 'goddess'},
    {word: 'οὐ/οὐκ/οὐχ', traduction: 'not'},
    {word: 'oὖν', traduction: 'therefore'},
    // {word: '', traduction: ''},
    // {word: '', traduction: ''},
    // {word: '', traduction: ''},
    // {word: '', traduction: ''},
    // {word: '', traduction: ''},
    // {word: '', traduction: ''},
    // {word: '', traduction: ''},
    // {word: '', traduction: ''},
    // {word: '', traduction: ''},
];